# Generated by Django 5.2.6 on 2025-09-10 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('input_json', models.JSONField(help_text='Raw input features as received from client')),
                ('prediction_label', models.CharField(choices=[('benign', 'Benign'), ('malignant', 'Malignant')], help_text='Predicted label (benign/malignant)', max_length=20)),
                ('probability_malignant', models.FloatField(help_text='Probability of malignancy (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('top_contributions', models.JSONField(blank=True, help_text='Top feature contributions as list of {feature, contribution}', null=True)),
                ('model_version', models.CharField(default='unknown', help_text='Version of the model used for prediction', max_length=50)),
                ('confirmed_label', models.IntegerField(blank=True, help_text='Doctor-confirmed outcome: 0=benign, 1=malignant', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the doctor confirmation was submitted', null=True)),
            ],
            options={
                'verbose_name': 'Prediction Submission',
                'verbose_name_plural': 'Prediction Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
